### ISSUE TITLE
Services - Vérifier les titres

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/Metawal-contents#13]
Par convention, il a été décidé de nommer les services par le nom de la donnée puis le type de service. La convention est suivie pour les dernières fiches éditées mais pas pour les fiches plus anciennes. Il faut les revoir et modifier l'ordre des infos.
Ex de dénomination correcte : Lignes du réseau TEC - Service de visualisation INSPIRE

**Comment by gdetry** [comment]
Les titres des geoservices ont été mis en conformité 
Nom de la donnée - Service de visualisation...
