### ISSUE TITLE
Adresse d'affichage des services dans WalonMap - remplacer agsDynUrls

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/Metawal-contents#23]
Voir avec Stéphane. Remplacer la requête agsDynUrls par la nouvelle requête WalOnMap. Attendre la v4 de Metawal ?

**Comment by gdetry** [comment]
Les requêtes agsDynUrls ont été remplacées par ADU lors de la repasse sur le catalogue (06/2016). Normalement, la requête WalOnMap doit systématiquement prendre ce paramètre sauf coquilles

**Comment by gdetry** [comment]
Cette tâche est considérée comme cloturée
